spring.application.name=dev-social-network
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_DATABASE:codefactory}
spring.datasource.username=${DB_USERNAME:codefactory}
spring.datasource.password=${DB_PASSWORD:codefactory}

# No auto-gestionar Docker Compose (el contenedor ya se levanta manualmente)
spring.docker.compose.enabled=false

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
